### PR TITLE
fix ender chest 

### PR DESCRIPTION
**Pull request by ghost**
and am not a noob the poeple that frow me away are noob 🔥

### CODE REVIEW

**Comment by ghost** [comment]
Have the forgetting 😑

**Comment by ghost** [comment]
@BlawoHD  my  enderchest wash working end its removed

**Comment by ghost** [comment]
@caspervanneck Why is it always taken out?

**Comment by ghost** [comment]
? @BlawoHD

**Comment by ghost** [comment]
@BlawoHD you can merge it

**Comment by ghost** [comment]
@BlawoHD  @kametan0730MC merge

**Comment by ghost** [comment]
???

**Comment by ghost** [comment]
@BlawoHD  this is ready for merge so

**Comment by kametan0730** [comment]
[Server thread/CRITICAL]: Error: "Call to a member function openAt() on null" (EXCEPTION) in "/src/pocketmine/block/EnderChest" at line 122

**Comment by kametan0730** [comment]
Fixed

**Pull request merged**
