### PR TITLE
1.4.1

### PR DESCRIPTION
**Pull request by Saxavlax001**
## Have you tested?
- [x] I have tested.
- [ ] I haven't tested.
I just wanted to update bluelight for my server but update is not ready because server has an error or two errors:
screenshot_2018-05-19-19-50-00-807_net fengberd minecraftpe_server
If someone can fix the problem,you can commit on my branch or tell me what i should change or add or delete.

### CODE REVIEW

**Comment by Saxavlax001** [comment]
Idk why scorepacketentry failed to add weird

**Comment by Saxavlax001** [comment]
Debug message here if it helps
[01:04:44] [Server thread/DEBUG]: Packet pocketmine\network\mcpe\protocol\BatchPacket 0xfe78da63e360606061600000006d0013
[01:04:44] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\network\mcpe\protocol\StartGamePacket::putVector3()" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/StartGamePacket" at line 185
[01:04:44] [Server thread/DEBUG]: #0 src/pocketmine/network/mcpe/protocol/DataPacket(90): pocketmine\network\mcpe\protocol\StartGamePacket->encodePayload()
[01:04:44] [Server thread/DEBUG]: #1 src/pocketmine/network/mcpe/RakLibInterface(208): pocketmine\network\mcpe\protocol\DataPacket->encode()
[01:04:44] [Server thread/DEBUG]: #2 src/pocketmine/Player(1196): pocketmine\network\mcpe\RakLibInterface->putPacket(pocketmine\Player object, pocketmine\network\mcpe\protocol\StartGamePacket object, boolean , boolean )
[01:04:44] [Server thread/DEBUG]: #3 src/pocketmine/Player(1158): pocketmine\Player->sendDataPacket(pocketmine\network\mcpe\protocol\StartGamePacket object, boolean , boolean )
[01:04:44] [Server thread/DEBUG]: #4 src/pocketmine/Player(1987): pocketmine\Player->dataPacket(pocketmine\network\mcpe\protocol\StartGamePacket object)
[01:04:44] [Server thread/DEBUG]: #5 src/pocketmine/Player(2135): pocketmine\Player->completeLoginSequence()
[01:04:44] [Server thread/DEBUG]: #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(106): pocketmine\Player->handleResourcePackClientResponse(pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket object)
[01:04:44] [Server thread/DEBUG]: #7 src/pocketmine/network/mcpe/protocol/ResourcePackClientResponsePacket(61): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleResourcePackClientResponse(pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket object)
[01:04:44] [Server thread/DEBUG]: #8 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(91): pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
[01:04:44] [Server thread/DEBUG]: #9 src/pocketmine/network/mcpe/protocol/BatchPacket(118): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket object)
[01:04:44] [Server thread/DEBUG]: #10 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(91): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
[01:04:44] [Server thread/DEBUG]: #11 src/pocketmine/Player(3218): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
[01:04:44] [Server thread/DEBUG]: #12 src/pocketmine/network/mcpe/RakLibInterface(143): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
[01:04:44] [Server thread/DEBUG]: #13 src/raklib/server/ServerHandler(97): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 192.168.2.4:45539, raklib\protocol\EncapsulatedPacket object, integer 0)
[01:04:44] [Server thread/DEBUG]: #14 src/pocketmine/network/mcpe/RakLibInterface(82): raklib\server\ServerHandler->handlePacket()
[01:04:44] [Server thread/DEBUG]: #15 src/pocketmine/network/Network(89): pocketmine\network\mcpe\RakLibInterface->process()
[01:04:44] [Server thread/DEBUG]: #16 src/pocketmine/Server(2568): pocketmine\network\Network->processInterfaces()
[01:04:44] [Server thread/DEBUG]: #17 src/pocketmine/Server(2321): pocketmine\Server->tick()
[01:04:44] [Server thread/DEBUG]: #18 src/pocketmine/Server(2200): pocketmine\Server->tickProcessor()
[01:04:44] [Server thread/DEBUG]: #19 src/pocketmine/Server(1779): pocketmine\Server->start()
[01:04:44] [Server thread/DEBUG]: #20 src/pocketmine/PocketMine(510): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /storage/emulated/0/PocketMine/, string /storage/emulated/0/PocketMine/, string /storage/emulated/0/PocketMine/plugins/)
[01:04:44] [Server thread/DEBUG]: Expected tick difference of at least 1, got 0 for pocketmine\entity\Item
[01:04:44] [Server thread/DEBUG]: Expected tick difference of at least 1, got 0 for pocketmine\entity\Item
[01:04:44] [RakLibServer thread/NOTICE]: Blocked x.x.x.x.x for 5 seconds

**Comment by Saxavlax001** [comment]
screenshot_2018-05-20-11-23-43-691_net fengberd minecraftpe_server

**Comment by WesleyVanNeck** [comment]
@poustmal sorry for saying but the repo is dead

**Comment by Saxavlax001** [comment]
It seems its dead.There isn't anyone to help this project but this software is the only one that my host supports for now and i can't change to another software that runs 1.4.0

**Comment by WesleyVanNeck** [comment]
there is a small for or spoon what evr you guys whant call it but i no pc right now so i cant work properly on it https://github.com/BlueLightDutch/BlueLight

**Comment by Saxavlax001** [comment]
ok when you can if you want,try to fix the issues here:https://github.com/RevivalTeam/BlueLight
Or make your own things to do the update

**Pull request closed without merging**
