### PR TITLE
look at code 

### PR DESCRIPTION
**Pull request by ghost**
then merge it it says TransactionQueue and not TransactionGroup

its copyd from genisys based software

### CODE REVIEW

**Comment by Saxavlax001** [comment]
Yes but solves armor duplications

**Comment by ghost** [comment]
All mcpe software comes from Pocketmine but Tesseract comes from both
Pocketmine & Genisys. So yeah.

**Comment by AvgZing** [comment]
@Qimie Actually, in detail: All mcpe softwares come from original pocketmine. We have:
Genisys (spoon)
Tesseract based off of genisys based off of pocketmine (spoon)
pmmp (spoon)
Bluelight based off of pmmp based off of pocketmine (spoon)
ClearSky based off of pmmp based off of pocketmine (fork)
Most others: Based off of either genisys which is based off of pocketmine, or based off of pmmp based off of pocketmine. Bottom line, all of them are based off of the original pocketmine-mp

**Comment by jrodr10** [comment]
@TheRoyalBlock finally someone gets it

**Comment by ghost** [comment]
1. I kinda get what ur saying.
2. Dont copy other code pls. At least edit  it. -_-

**Comment by Saxavlax001** [comment]
I had copied the code carefully and tested.

**Comment by AvgZing** [comment]
But in the end its still copying code.

**Pull request closed without merging**
