### PR TITLE
Trying to fix the ride bug in the Pig.php file

### PR DESCRIPTION
**Pull request by MalakasPlayzMC**
Sinse I was not able to ride pigs, only horses ect. I modified the Pig.php to make it work. Could you add it?

### CODE REVIEW

**Comment by haniokasai** [comment]
[03:15:09] [Server thread/CRITICAL]: ParseError: "syntax error, unexpected 'default' (T_DEFAULT)" (EXCEPTION) in "/src/pocketmine/entity/Pig" at line 126

**Comment by MalakasPlayzMC** [comment]
Now I get the error: [07:23:45] [Server thread/CRITICAL]: ClassNotFoundException: "Class pocketmine\utils\Range not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
[07:23:45] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump

**Comment by MalakasPlayzMC** [comment]
I created a phar of BlueLight (with the modified version of Pig.php) and I was able to ride the pig but with the following result:

videotogif_2017 04 09_13 18 09

I modified
`	public function getRidePosition(){
		return [-0.02, 1, 0.19];
	}`
to
`	public function getRidePosition(){
		return [-0.02, 2.5, 0.19];
	}`
but nothing. Anyone can help me?

**Comment by MalakasPlayzMC** [comment]
How to fix the ride position bug?!?!?! Anyone please? At least modify the Pig.php file with this one:
https://raw.githubusercontent.com/MalakasPlayzMC/BlueLight/fa1561ccf71999977025b231dde8be324c5d34df/src/pocketmine/entity/Pig.php

**Comment by YaBoiDevelops** [comment]
EAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCKEAT MY COCK

**Comment by ICrashHD** [comment]
www.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gotti

**Comment by MalakasPlayzMC** [comment]
What the...? I ask for help and you send me porn videos and sexual messages? The moderators should ip-ban you from the BlueLight source code

**Comment by kametan0730** [comment]
thank you for your pullrequest

**Pull request merged**
