### PR TITLE
Update to 1.1

### PR DESCRIPTION
**Pull request by ghost**
## Have you tested?
- [x] I have tested.
- [ ] I haven't tested.

### CODE REVIEW

**Comment by ExaSonit** [comment]
it work correctly for 1.1?

**Comment by ghost** [comment]
it doesn't work
server kicks me "logged out due to Login timeout"

photo5874998903236045217 1
photo5874998903236045218

**Comment by haniokasai** [comment]
it is not necessary that remove pervious packet number

**Comment by ExplodingSquad** [comment]
PocketMine Team Is Working For 1.1.0 Lets See The Code In There ;)

**Comment by ExplodingSquad** [comment]
USE 1.1.0.55

**Pull request closed without merging**
